apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "multicalchart.name" . }}-frontend
  labels:
    app: {{ template "multicalchart.name" . }}-frontend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: frontend
spec:
  replicas: {{ .Values.frontendReplicaCount }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "multicalchart.name" . }}
        name: js-calc-frontend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: calcfrontend
          image: "{{ .Values.image.repository }}/{{ .Values.image.frontendImage }}:{{ .Values.image.frontendTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http         
              protocol: TCP
          env: 
            - name: "ENDPOINT"
              value: "{{ .Release.Name }}-calc-backend-svc"
            - name: "INSTRUMENTATIONKEY"
              valueFrom:
                secretKeyRef:
                  name: appinsightsecret
                  key: appinsightskey
            - name: "PORT"
              value: "3000"
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "multicalchart.name" . }}-backend
  labels:
    app: {{ template "multicalchart.name" . }}-backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: backend
spec:
  replicas: {{ .Values.backendReplicaCount }}
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "multicalchart.name" . }}
        name: js-calc-backend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: calcbackend
          image: "{{ .Values.image.repository }}/{{ .Values.image.backendImage }}:{{ .Values.image.backendTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3001
              name: http         
              protocol: TCP
          env: 
            - name: "INSTRUMENTATIONKEY"
              valueFrom:
                secretKeyRef:
                  name: appinsightsecret
                  key: appinsightskey
            - name: "PORT"
              value: "3001"
          livenessProbe:
            httpGet:
              path: /ping
              port: 3001
          readinessProbe:
            httpGet:
              path: /ping
              port: 3001
