apiVersion: v1
kind: Service
metadata:
  name: {{ include "multicalculatorcanary.fullname" . }}-frontend-svc
  labels:
    {{- include "multicalculatorcanary.labels" . | nindent 4 }}
    role: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "multicalculatorcanary.selectorLabels" . | nindent 4 }}
    role: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "multicalculatorcanary.fullname" . }}-backend-svc
  labels:
    {{- include "multicalculatorcanary.labels" . | nindent 4 }}
    role: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "multicalculatorcanary.selectorLabels" . | nindent 4 }}
    role: backend


