replicaCount: 2
horizonalPodAutoscaler: false

image:
  repository: denniszielke
  pullPolicy: Always
  frontendImage: js-calc-frontend
  backendImage: js-calc-backend
  frontendTag: latest
  backendTag: latest

nameOverride: ""
fullnameOverride: ""

introduceRandomResponseLag: true # if set to true there will be random response lags and faults in the backend
introduceRandomResponseLagValue: 3 # seconds of the response lag
dependencies:
  useAzureRedis: false # use azure redis cache - specify redisHostValue and redisKeyValue
  redisHostValue: xxx.redis.cache.windows.net # redis host (no ssl)
  redisKeyValue: XXXX+= # redis auth key
  usePodRedis: false # use a redis sidecar in the frontend pod
  useAppInsights: false # use application insights - specify appInsightsSecretValue
  appInsightsSecretValue: dummyValue # application insights instrumentation key
  useIngress: false # use ingress - specify service.dnsName

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  tls: false
  class: nginx # traefik
  host: devapis1.westeurope.cloudapp.azure.com
  annotations: {
    kubernetes.io/ingress.class: nginx,
    nginx.ingress.kubernetes.io/rewrite-target: /,
    cert-manager.io/cluster-issuer: letsencrypt
  }

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 20m
    memory: 65Mi

nodeSelector: {}

tolerations: []

affinity: {}
