name: js-calc-frontend

on: 
  push:
    paths:
      - 'apps/js-calc-frontend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB }}
        DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
      run: |
        ls -l
        cd apps/js-calc-frontend
        ls -l
        echo "Docker login"
        docker login -u $DOCKER_HUB -p $DOCKER_HUB_SECRET
        echo "Running docker build"
        docker build . --tag denniszielke/js-calc-frontend:latest
        echo "Pushing image"
        docker push denniszielke/js-calc-frontend:latest
        echo "Done"
